### ISSUE TITLE
[Join Request] Authorship access

### ISSUE THREAD

**Issue by roadkizzle** [BSData/Dystopian-Legions#1]
I am trying to upload a battlescribe repository. Can I get Authorship access?

**Comment by amis92** [comment]
Please elaborate. What exactly are you trying to do?

**Comment by stevecodeguy** [comment]
Roadkizzle is attempting to gain access to author files for Dystopian Legions. I've been trying to assist him with this. He has files located here : https://github.com/roadkizzle/Dystopian-Legions-Repository

He needs to be able to pull those files to the BSData/Dysopian-Legions repository.

**Comment by amis92** [comment]
Ok, I've added this repo to Others, so @steve990 you should have write access to it. Also, I've invited @roadkizzle to the organization. Both of you should be able to manage the repo.
